{{ config(
    materialized='semantic_view'
) }}

tables (
    {{ ref('customers') }} primary key (CUSTOMER_ID) comment='The table contains records of customers...',
    {{ ref('orders') }} comment='The table contains records of customer orders...'
)
	relationships (
		ORDERS_TO_CUSTOMERS as ORDERS(CUSTOMER_ID) references CUSTOMERS(CUSTOMER_ID)
	)
	facts (
		ORDERS.TOTAL_AMOUNT as TOTAL_AMOUNT comment='The total amount of the order.'
	)
	dimensions (
		CUSTOMERS.CUSTOMER_ID as CUSTOMER_ID comment='Unique identifier assigned to each customer.',
		CUSTOMERS.EMAIL as EMAIL comment='Customer email addresses.',
		CUSTOMERS.FIRST_NAME as FIRST_NAME comment='The first name of the customer.',
		CUSTOMERS.LAST_NAME as LAST_NAME comment='Customer last names.',
		ORDERS.CUSTOMER_ID as CUSTOMER_ID comment='Unique identifier for the customer who placed the order.',
		ORDERS.DELIVERY_TIME_FROM_COLLECTION as DELIVERY_TIME_FROM_COLLECTION comment='The time elapsed between collection and delivery measured in a numeric unit.',
		ORDERS.DELIVERY_TIME_FROM_ORDER as DELIVERY_TIME_FROM_ORDER comment='The number of time units between when an order was placed and when it was delivered.',
		ORDERS.ORDER_ID as ORDER_ID comment='Unique identifier for each order in the system.',
		ORDERS.ORDER_STATUS as ORDER_STATUS comment='The current status of the order in its fulfillment lifecycle.',
		ORDERS.STORE_ID as STORE_ID comment='The identifier for the store where the order was placed.',
		ORDERS.ORDERED_AT as ORDERED_AT comment='The date and time when the order was placed.'
	)
	metrics (
		ORDERS.REVENUE as sum(total_amount) with synonyms=('sales','total revenue') comment='Revenue is the sum of total_amount. Some team members also call it sales. When we refer to a year, we mean our fiscal year which starts in October.'
	)
	comment='This semantic view is for defining order, customer and deliveries metrics.'
	ai_sql_generation 'A fiscal year starting in October means FY2026 runs from October 2025 through September 2026.'
	with extension (CA='{"tables":[{"name":"CUSTOMERS","dimensions":[{"name":"CUSTOMER_ID","sample_values":["56","33","66"]},{"name":"EMAIL","sample_values":["bambie.davidwitz@gmail.com","cyndi.root@gmail.com","crysta.duro@gmail.com"]},{"name":"FIRST_NAME","sample_values":["Sienna","Oskar","Cyndi"]},{"name":"LAST_NAME","sample_values":["Lopez","Treat","Root"]}]},{"name":"ORDERS","dimensions":[{"name":"CUSTOMER_ID","sample_values":["4","38","15"]},{"name":"DELIVERY_TIME_FROM_COLLECTION","sample_values":["75","30"]},{"name":"DELIVERY_TIME_FROM_ORDER","sample_values":["150","25"]},{"name":"ORDER_ID","sample_values":["79e80a1d-c39d-49d5-850e-b03802ed1654","74228028-7a52-49ff-b64a-98a37bb58e8c","6473bad8-2748-41f9-bdd2-86f43e9e0400"]},{"name":"ORDER_STATUS","sample_values":["delivered","pending","ordered"]},{"name":"STORE_ID","sample_values":["1"]}],"facts":[{"name":"TOTAL_AMOUNT","sample_values":["42.65","18.96","9.56"]}],"metrics":[{"name":"REVENUE"}],"time_dimensions":[{"name":"ORDERED_AT","sample_values":["2025-04-04T00:00:00.000+0000","2025-09-18T00:00:00.000+0000","2025-03-19T00:00:00.000+0000"]}]}],"relationships":[{"name":"ORDERS_TO_CUSTOMERS","relationship_type":"many_to_one","join_type":"inner"}],"verified_queries":[{"name":"\\"0;1\\"","sql":"SELECT o.order_id /* order facts */, o.ordered_at, o.order_status, o.total_amount, o.store_id, o.delivery_time_from_order, o.delivery_time_from_collection, c.customer_id /* customer dimension */, c.first_name, c.last_name, c.email FROM orders AS o INNER JOIN customers AS c ON o.customer_id = c.customer_id","question":"What are the complete order details combined with customer information?","verified_at":1771838045,"verified_by":"Semantic Model Generator"},{"name":"\\"Who are the top 5 customers based on sales in 2026?\\"","sql":"SELECT\\n  c.customer_id,\\n  c.first_name,\\n  c.last_name,\\n  SUM(o.total_amount) AS revenue\\nFROM\\n  orders AS o\\n  INNER JOIN customers AS c ON o.customer_id = c.customer_id\\nWHERE\\n  o.ordered_at >= ''2025-10-01''\\n  AND o.ordered_at < ''2026-10-01''\\nGROUP BY\\n  c.customer_id,\\n  c.first_name,\\n  c.last_name\\nORDER BY\\n  revenue DESC NULLS LAST\\nLIMIT\\n  5\\n  /* Generated by Cortex Analyst (request_id: 79fb1def-d64f-483a-a221-bc66ffe493ad) */","question":"Who are the top 5 customers based on sales in 2026?","verified_at":1771839683,"verified_by":"TIMO","use_as_onboarding_question":false}]}');